[package]
name = "rebeldb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
blake3 = "1.5.5"
bytes = "1.9.0"
hex = "0.4.3"
linkme = "0.3.31"
thiserror = "2.0.11"
tracing = "0.1.41"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
