[package]
name = "rebeldb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
blake3 = "1.5.5"
hex = "0.4.3"
linkme = "0.3.31"
thiserror = "2.0.11"
tracing = "0.1.41"
wasm-encoder = "0.223.0"
