[package]
name = "rebeldb-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

[profile.release]
lto = true
opt-level = 's' # or 'z' for size optimization
