[workspace]
members = [
  "crates/huly",
  "crates/huly-cli",
  "crates/rebeldb",
  "crates/rebeldb-cli", "crates/rebeldb-core",
  "crates/rebeldb-runtime",
  "crates/rebeldb-wasm", "rebel",
]
resolver = "2"
