[package]
name = "rebel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
smol_str = "0.3.2"
ssh2 = "0.9.4"
whoami = "1.4.1"

[dev-dependencies]
tempfile = "3.10.1"
